name: Deploy Sanity
on:
    push:
        branches: [master]
jobs:
    sanity_deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@master
            - name: Install Dependencies
              run: yarn install
            - name: Deploy
              run: yarn deploy
